feat(chat): call ui updated
Satellite-im/WarpGUI pull request #364
Opened 2022-11-21 13:13 UTC by molimauro

### What this PR does 📖
- Call ui updates

### Which issue(s) this PR fixes 🔨
- Resolve #

### Special notes for reviewers 🗒️
Added the first username letter in the Media user box, lmk if it doesnt look good. We should put the Satellite icon later 

### Additional comments 🎤

2022-11-21 14:27 UTC, InfamousVague requested changes
small changes then looks good for QA

2022-11-21 14:27 UTC, InfamousVague commented on src/components/media/styles.scss
> +      margin-top: 12px;
we should use consistent padding and margin so either 0.5rem or 1rem, the gap let's set to 1rem

2022-11-21 14:27 UTC, InfamousVague commented on src/ui_kit/src/profile_picture/styles.scss
> +  border-radius: 50%;
Either of these work, doesn't matter to me 😁

2022-11-21 14:27 UTC, InfamousVague commented on src/components/media/media/styles.scss
> +      font-size: 2rem;
we should use one of the font sizes from the theme so `var(--text-size)` may be best, there is also smaller

2022-11-21 14:27 UTC, InfamousVague commented on src/components/media/media/styles.scss
> +        height: 80px;
let's do 40x40px for now just to keep it the same as everything else, unless it's larger on profile then we can use that

2022-11-21 14:27 UTC, InfamousVague commented on src/components/main/compose/messages/styles.scss
> +    margin: 16px 0;
for now let's omit this just so our margins are consistent, makes it easier to find and replace later if/when we change it

2022-11-21 14:41 UTC, molimauro commented
Done, thanks for the feedback!!

2022-11-21 17:09 UTC, phillsatellite commented
Noticed while testing that we only show 1 user in the call and a side note from Matt, the call should be able to display many users in a grid shrinking the users but maintaining aspect ratio.

![image](https://user-images.githubusercontent.com/93608357/203117382-1ee578c3-c292-44c5-9a7d-f6cfe81f5899.png)

2022-11-21 17:22 UTC, molimauro commented
I can increase the number of users but they will keep the same size regardless of the resize in place. I think we should merge this one and focus later on the user media resize, what do you think?

2022-11-21 20:20 UTC, stavares843 commented
also agree

2022-11-22 16:03 UTC, phillsatellite commented
Sounds good to me!

2022-11-22 16:29 UTC, phillsatellite approved these changes

2022-11-22 18:16 UTC, InfamousVague approved these changes

2022-11-22 18:16 UTC, merged